import userImage from "../assets/image 1.png";
export const investorsList = [
  {
    id: 0,
    image: userImage,
    name: "Rajesh Sinha",
    email: "rajest@gmail.com",
    investments: "$12M",
    deals: "03",
    type: "Logn Term",
    status: "active",
  },
  {
    id: 1,
    image: userImage,
    name: "Rajesh Sinha",
    email: "rajest@gmail.com",
    investments: "$12M",
    deals: "03",
    type: "Logn Term",
    status: "inactive",
  },
  {
    id: 2,
    image: userImage,
    name: "Rajesh Sinha",
    email: "rajest@gmail.com",
    investments: "$12M",
    deals: "03",
    type: "Logn Term",
    status: "active",
  },
  {
    id: 3,
    image: userImage,
    name: "Rajesh Sinha",
    email: "rajest@gmail.com",
    investments: "$12M",
    deals: "03",
    type: "Logn Term",
    status: "active",
  },
];
